# -*- coding: utf-8 -*-
"""Trabalho de recuperação de mobile

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KwnB1SsSAlLuBIDmUKOi0hM8F4ldvhxy
"""

# Solicita as três notas ao usuário
nota1 = float(input("Digite a primeira nota: "))
nota2 = float(input("Digite a segunda nota: "))
nota3 = float(input("Digite a terceira nota: "))

# Calcula a média das notas
media_final = (nota1 + nota2 + nota3) / 3

# Exibe a média calculada
print(f"A média final das notas é: {media_final:.2f}")

# Faz o teste condicional para aprovação ou reprovação
if media_final >= 60:
    print("Situação: VOCÊ FOI APROVADO")
else:
    print("Situação: VOCÊ FOI REPROVADO")